### ISSUE TITLE
[Bug]: Composables build issue

### ISSUE THREAD

**Issue by bartoszherba** [vuestorefront/magento2#200]
### Expected Behavior

Build finish successfully

### Actual Behavior

- Running `yarn build:composables` command yield TS semantic error
- Branch: develop

yarn build:composables

```yarn run v1.22.11
$ cd packages/composables && yarn build
$ rimraf lib && rollup -c

src/index.ts → lib/index.cjs.js, lib/index.es.js...
[!] (plugin rpt2) Error: <root>/packages/composables/src/composables/useCart/index.ts(198,51): semantic error TS2339: Property 'downloadable_product_links' does not exist on type 'Product'.
src/composables/useCart/index.ts
Error: <root>/packages/composables/src/composables/useCart/index.ts(198,51): semantic error TS2339: Property 'downloadable_product_links' does not exist on type 'Product'.
    at error (<root>/node_modules/rollup/dist/shared/rollup.js:158:30)
    at throwPluginError (<root>/node_modules/rollup/dist/shared/rollup.js:21741:12)
    at Object.error (<root>/node_modules/rollup/dist/shared/rollup.js:22415:20)
    at Object.error (<root>/node_modules/rollup/dist/shared/rollup.js:21917:38)
    at RollupContext.error (<root>/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at <root>/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11```
   ....

### Possible Solution

Missing ProductInterface type definitions must be updated in **packages/api-client/src/types/GraphQL.ts**

### Steps to reproduce

1. Switch to a develop branch
2. Run `yarn build:composables` from a project root.

### What version of Magento 2 integration are you using?

2.4.2

### What version of Node.js are you using?

v14.17.6

### What browser (and version) are you using?

Chrome (irrelevant)

### What operating system (and version) are you using?

macOS

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bartoszherba** [comment]
@KevinGorjan 
Bug was related to an invalid local environment setup (built with npm once instead of yarn). I created a PR to refine readme so it is now clear of what tools are supported and how to setup env, in more details.
