### ISSUE TITLE
Cannot connect to Magento, "TypeError: Only absolute URLs are supported" + useCart/load 500 error

### ISSUE THREAD

**Issue by IMakeTheSites** [vuestorefront/magento2#73]
## Expected Behavior

VSF should connect to my Magento site and load products

## Current Behavior

No products appear on the page, but I receive connection errors in the console:
 ERROR  [VSF][error] [Network error]: TypeError: Only absolute URLs are supported                                 21:27:31

 ERROR  [VSF][error] useCart/load Request failed with status code 500                                             21:27:31

  at createError (/Users/markwlodawski/dev/vsf2ports-magento/magento2/node_modules/axios/lib/core/createError.js:16:15)
  at settle (/Users/markwlodawski/dev/vsf2ports-magento/magento2/node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (/Users/markwlodawski/dev/vsf2ports-magento/magento2/node_modules/axios/lib/adapters/http.js:260:11)
  at IncomingMessage.emit (events.js:327:22)
  at endReadableNT (_stream_readable.js:1220:12)
  at processTicksAndRejections (internal/process/task_queues.js:84:21)

## Possible Solution

I'm not sure whether this is related to Axios, Apollo, or 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I actually first had this issue a few days ago when my Magento site was still located only at its static IP address, so I spent a couple of days directing the nameservers of mqexports.com to the Magento installation, hosted on Google Cloud services, hoping the problem would go away. Apparently, it wasn't the source of the problem, because now the issue is still there.

## Your Environment

* Version used: VSF 2, Magento 2.4.2
* Browser Name and version: Chrome 90
* Operating System and version (desktop or mobile): MacBook Pro 2019
* Link to your project: https://github.com/IMakeTheSites/vsf-exports
My .env file's content:

MAGENTO_GRAPHQL=https://mqexports.com/graphql
MAGENTO_EXTERNAL_CHECKOUT=https://mqexports.com
MAGENTO_EXTERNAL_CHECKOUT_SYNC_PATH=/vue/cart/sync

**Comment by drew-webscale** [comment]
I am seeing the same error with my local setup now. I had it working before but for some reason am getting the error "Only absolute URLs are supported" now. It looks like the graphql connection is working okay:

```
 ERROR  [VSF][error]:  [GraphQL error]: Message: The current customer isn't authorized., Location: [column: 16, line: 1], Path: customer


 ERROR  Only absolute URLs are supported

  at getNodeRequestOptions (node_modules/node-fetch/lib/index.js:1327:9)
  at node_modules/node-fetch/lib/index.js:1440:19
  at new Promise (<anonymous>)
  at fetch (node_modules/node-fetch/lib/index.js:1437:9)
  at fetch (node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
  at node_modules/graphql-request/dist/index.js:186:42
  at step (node_modules/graphql-request/dist/index.js:63:23)
  at Object.next (node_modules/graphql-request/dist/index.js:44:53)
  at node_modules/graphql-request/dist/index.js:38:71
  at new Promise (<anonymous>)

```
